### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by leopheard** [XavierBerger/RPi-Monitor#264]
Hi there,

Thanks for this awesome software! One thing - is there a dark theme? Or can I edit one of the .css files to make it a dark background? If so, do you know which file and where I could add the html to?

**Comment by alanmilinovic** [comment]
That would be awesome!

**Comment by DaniW42** [comment]
@leopheard @amilino 

This might be a **very!** dirty workaround, but you could add the following lines to your `rpimonitor.css`

### Make a backup!
Of course, as always, make a backup first! As root user run:
`cp /usr/share/rpimonitor/web/css/rpimonitor.css /usr/share/rpimonitor/web/css/rpimonitor.css.bak`

### Edit .css file
nano in to your rpimonitor.css.bak
`nano /usr/share/rpimonitor/web/css/rpimonitor.css`

and add these lines to the end of your file:
```
/* 'Enable' Dark Mode workaround */
body {
  color: #fff !important;
  background-color: #0e0e3d !important;
}

.panel-body {
  background-color: #0e0e3d !important;
}

.modal-content {
  color: #000 !important;
}

.btn {
    background-color: darkgray !important;
}

select {
    color: #000 !important;
}

input[type="button"] {
    color: #000 !important;
}
```
### Optional: Adjust colours
If you want to adjust colours check [CSS Colours](https://www.w3schools.com/cssref/css_colors.asp) by awesome w3schools.com. Would be nice to know which settings you prefer!

### In case something bricks: revert to original state
To revert back to your original file simply delete the lines or get a fresh rpimonitor.css from github.
`wget https://raw.githubusercontent.com/XavierBerger/RPi-Monitor/master/src/usr/share/rpimonitor/web/css/rpimonitor.css -O /usr/share/rpimonitor/web/css/rpimonitor.css`

### This won't be persistent during updates
The styles will be overwritten as soon as rpimonitor updates the file during an update. Would be nice to see a clean solution by somebody who is more into stuff like this than me.

**What it looks like using the settings above:**
![image](https://user-images.githubusercontent.com/21097466/89631841-9f2bbf00-d8a1-11ea-93d3-45519e31615f.png)

Unfortunately, its pretty hard to read the stats, this would need some further tweaking...
![image](https://user-images.githubusercontent.com/21097466/89632554-ad2e0f80-d8a2-11ea-9e8f-11eb8ad3c9d4.png)

I don't have any Addons active, so it is very likely that this pages also need some tweaking.

Show some love to @XavierBerger for this nice tool!

**Comment by Synetech** [comment]
I changed it to be a dark-grey and added these rules to hide the lines and to fix the SVG text inside the gauges, and fixed the text of the popups to be visible:

```
hr {
    border-color: #282923 !important;
}
.column-fluid {
    column-rule-color: #282923 !important;
}

div.justgage svg text {
    filter: contrast(0%) !important;
}
a#packages+div.popover.fade.in.bottom {
    color: #000 !important;
}
```

And since RPi-Monitor doesn't update much, it shouldn't be a problem. 🤷

**Comment by EdSforzati** [comment]
For those interested:
This is the complete CSS addition I figured out worked aesthetically and made everything able to be read and understood.
Add to the end of `/usr/share/rpimonitor/web/css/rpimonitor.css`:

**NB:** Works for everything I have. I haven't used any `Addons` and didn't test badges and such.

![image](https://user-images.githubusercontent.com/18356103/174753242-9e39725e-91ff-443a-965f-7f4dbc437abe.png)
![image](https://user-images.githubusercontent.com/18356103/174753303-f28fff44-40e2-4972-b577-4c513ce51194.png)
```css
/*--- -- --- -- ---*/
/* -- DARK MODE -- */
/*--- -- --- -- ---*/

/* Nav & Menu */
.dropdown-menu,
.navbar-inverse .navbar-nav > .active > a,
.navbar-inverse .navbar-nav > .active > a:focus,
.navbar-inverse .navbar-nav > .active > a:hover {
    background-color: #3c3c3c !important;
}

.dropdown-menu > li > a {
    color: gray !important;
}

.dropdown-menu > li > a:hover {
    background-color: #6a6a6a !important;
    color: white !important;
}

body {
    background-color: #1a1a1a !important;
}

/* Status */
.list-group-item {
    background-color: #1a1a1a !important;
    color: white !important;
}

hr {
    border-color: black !important;
}

.column-fluid {
    column-rule-color: black !important;
}

.justgage svg text {
    filter: contrast(0%) !important;
}

/* Statistics */
td {
    color: white;
}

.legendColorBox,
.legendLabel {
    background-color: #3c3c3c;
    color: lightgray;
}

.btn,
input[type="button"],
select {
    background-color: #222222;
    color: lightgray;
}

.btn:hover,
input[type="button"]:hover,
select:hover {
    color: gray;
}

/* Addons */
.panel-default > .panel-heading {
    background-color: #6a6a6a !important;
    color: white !important;
}

.panel-body {
    background-color: #3c3c3c;
    color: white;
}

/* Options */
.modal-content {
    background-color: #3c3c3c !important;
    color: white;
}
/*--- -- --- -- ---*/
/* -- DARK MODE -- */
/*--- -- --- -- ---*/
```

**Comment by alanmilinovic** [comment]
> For those interested: This is the complete CSS addition I figured out worked aesthetically and made everything able to be read and understood. Add to the end of `/usr/share/rpimonitor/web/css/rpimonitor.css`:
> 
> **NB:** Works for everything I have. I haven't used any `Addons` and didn't test badges and such.
> 
> ![image](https://user-images.githubusercontent.com/18356103/174753242-9e39725e-91ff-443a-965f-7f4dbc437abe.png) ![image](https://user-images.githubusercontent.com/18356103/174753303-f28fff44-40e2-4972-b577-4c513ce51194.png)
> 
> ```css
> /*--- -- --- -- ---*/
> /* -- DARK MODE -- */
> /*--- -- --- -- ---*/
> 
> /* Nav & Menu */
> .dropdown-menu,
> .navbar-inverse .navbar-nav > .active > a,
> .navbar-inverse .navbar-nav > .active > a:focus,
> .navbar-inverse .navbar-nav > .active > a:hover {
>     background-color: #3c3c3c !important;
> }
> 
> .dropdown-menu > li > a {
>     color: gray !important;
> }
> 
> .dropdown-menu > li > a:hover {
>     background-color: #6a6a6a !important;
>     color: white !important;
> }
> 
> body {
>     background-color: #1a1a1a !important;
> }
> 
> /* Status */
> .list-group-item {
>     background-color: #1a1a1a !important;
>     color: white !important;
> }
> 
> hr {
>     border-color: black !important;
> }
> 
> .column-fluid {
>     column-rule-color: black !important;
> }
> 
> .justgage svg text {
>     filter: contrast(0%) !important;
> }
> 
> /* Statistics */
> td {
>     color: white;
> }
> 
> .legendColorBox,
> .legendLabel {
>     background-color: #3c3c3c;
>     color: lightgray;
> }
> 
> .btn,
> input[type="button"],
> select {
>     background-color: #222222;
>     color: lightgray;
> }
> 
> .btn:hover,
> input[type="button"]:hover,
> select:hover {
>     color: gray;
> }
> 
> /* Addons */
> .panel-default > .panel-heading {
>     background-color: #6a6a6a !important;
>     color: white !important;
> }
> 
> .panel-body {
>     background-color: #3c3c3c;
>     color: white;
> }
> 
> /* Options */
> .modal-content {
>     background-color: #3c3c3c !important;
>     color: white;
> }
> /*--- -- --- -- ---*/
> /* -- DARK MODE -- */
> /*--- -- --- -- ---*/
> ```

You are missing white color on body element.

**Comment by EdSforzati** [comment]
Hi @alanmilinovic, thanks for the tip!
I actually remembered having it, but took it out for some reason I could _not_ remember... :thinking: 

I just went to test again, and now I recall the reason:
With this specified, it leads to the issue on the statistics screen where the hover item's text is completely unreadable, and I actually spent quite some time trying to fix it!
```css
body {
    background-color: #1a1a1a !important;
    color: white !important;
}
```
![color: white Issue](https://user-images.githubusercontent.com/18356103/174979950-8485c3e0-6757-400d-a5b6-2d8dd4e59e66.png)

But by just specifying the `background-color` in the `body` block, we avoid that and end up with this nice result:
![Readable Hover Text](https://user-images.githubusercontent.com/18356103/174980730-43dbc0ad-7878-4886-85cf-de6143798a85.png)

I did put the `color: white;` in other places as required.
